In [ ]:
# syntax of if statement
# if test expression
    # statement

In [ ]:
name = 'sayantan'     #repeating the names
for i in range(7):
  print(name)

sayantan
sayantan
sayantan
sayantan
sayantan
sayantan
sayantan


In [ ]:
# if the number is positive print a message
number = 12
if number>5:
  print(number, 'is a positive number')
if number<0:
  print (number, 'is a negative')

12 is a positive number


In [ ]:
number = -64
if number>5:
  print(number, 'is a positive number')
if number<0:
  print (number, 'is a negative')

-64 is a negative


In [ ]:
#syntax for if else loop (loop means this if, elif and else)
# if test expression
    # statements
# else:
   #statements

In [ ]:
# programme to check wheather a number is positive or zero
number=10
if number >=0:
  print (number, 'is a positive integer')
else:
  print ('is not a positive integer')


10 is a positive integer


In [ ]:
# programme wheather a a number is +,- or 0 #(remeber colons if elif else and after that print has some gap, carefull on == )
number=14
if number>0:
  print (number, 'is a positive integer')
elif number==0:
  print (number,'is zero')
else:
  print(number,'is a negative number')

14 is a positive integer


In [ ]:
x=12              #simple arithmatics
y=21
print(x+y)
print(x-y)
print(x*y)
print(x/y)

33
-9
252
0.5714285714285714


In [ ]:
celsius= float(35)                                                  #if want to use(°) then use float (celsius to fahrenheit convert)
fahrenheit= (celsius*1.8)+32
print (f"{celsius}° celsius is equal to {fahrenheit}° fahrenheit")

35.0° celsius is equal to 95.0° fahrenheit


In [ ]:
import numpy as np
p= np.array([[1,2,3],[7,2,5]]) # import numpy and p & q defined with ([[x]])
                               # always p & q need same number of digits
q= np.array([[3,4,5],[4,5,7]])
print(p)
print(q)


[[1 2 3]
 [7 2 5]]
[[3 4 5]
 [4 5 7]]


In [ ]:
print(np.subtract(p,q))

[[-2 -2 -2]
 [ 3 -3 -2]]


In [ ]:
number=-100
if number<0:
  print (number, 'it is negative integer')
elif number ==0:
  print (number,  'it is 0')
else:
  print (number, 'positive integer')

-100 it is negative integer


In [ ]:
#syntax for loop                      #s=o and for i in the list
#for variable in sequence
List=[1,2,12,14,17,19,29]
s=0
for i in List:
  s=s+i
print ('sum of all items of the List is',s)

sum of all items of the List is 94


In [ ]:
a=range(10)
print(a)

range(0, 10)


In [ ]:
del list                 #if the list is collable (creating back to back numbers)
print (list(range(20)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
print (list(range(1,20,3))) # (number from 1 to 20, interval of 3)

[1, 4, 7, 10, 13, 16, 19]


In [ ]:
mark = int(input("Enter the student's mark"))  #students marks grading

if mark >= 90 and mark <= 100:
    print("Grade A")
elif mark >= 80 and mark < 90:
    print("Grade B")
elif mark >= 70 and mark < 80:
    print("Grade C")
elif mark >= 60 and mark < 70:
    print("Grade D")
else:
    print("Grade F")

Enter the student's mark12
Grade F


In [ ]:
mark=int(input('enter the number'))
if mark >=90 and mark <100:
    print ('grade A')
elif mark >=80 and mark <90:
    print ('grade B')
elif mark >=70 and mark <80:
    print ('grade C')
else:
    pass
    print ('grade D')

enter the number12
grade D


In [ ]:
import numpy as np                           # matrix arithmatics
p=np.array([[1,3,5,6],[2,6,7,8]])
q=np.array([[2,4,6,7],[5,7,8,9]])
print(np.add(p,q))
print(np.subtract(p,q))
print(np.multiply(p,q))
print(np.divide(p,q))

[[ 3  7 11 13]
 [ 7 13 15 17]]
[[-1 -1 -1 -1]
 [-3 -1 -1 -1]]
[[ 2 12 30 42]
 [10 42 56 72]]
[[0.5        0.75       0.83333333 0.85714286]
 [0.4        0.85714286 0.875      0.88888889]]


In [ ]:
p=np.array ([[2,5,1],[6,7,9],[1,2,3]])        #dot products of matrix
q=np.array ([[4,5,2],[7,9,8],[5,7,9]])
print(np.dot(p,q))

[[ 48  62  53]
 [118 156 149]
 [ 33  44  45]]


In [ ]:
mark= int(input('enter the mark'))
if mark >=90 and mark <100:
    print ('grade A')
elif mark >=80 and mark <90:
    print ('grade B')
elif mark >=70 and mark <80:
    print ('grade C')
else:
    print ('grade D')

enter the mark45
grade D


In [ ]:
a=[[1,4,5],                       #transpose of matrix
   [1,6,8],
   [3,9,8]]
res= [[0,0,0],
      [0,0,0],
      [0,0,0]]
for x in range (len(a)):
  print(a[x])
pass
for y in range (len(a[0])):
  res[y][x]=a[x][y]
print ('after transpose')

[1, 4, 5]
[1, 6, 8]
[3, 9, 8]
after transpose


In [ ]:
matrix = []                                                                     #matrix transpose with user input
for i in range(3):
    numbers = input(f"Enter 3 integers separated by spaces for row {i+1}: ")
    row = [int(num) for num in numbers.split()]
    matrix.append(row)
print("\nMatrix Transpose:")
for col in range(3):
    for row in range(3):
        print(matrix[row][col], end=" ")
print()

Enter 3 integers separated by spaces for row 1: 1 4 8
Enter 3 integers separated by spaces for row 2: 3 4 6
Enter 3 integers separated by spaces for row 3: 2 5 7

Matrix Transpose:
1 3 2 4 4 5 8 6 7 


In [ ]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9] ])
transpose = matrix.T
print("Original Matrix:")
print(matrix)
print("\nTranspose of the matrix:")
print(transpose)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of the matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Transpose of the matrix:\n",matrix.T)


Transpose of the matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import numpy as np
matrix = []
for i in range(3):
    row = list(map(int, input(f"Enter 3 numbers for row {i+1}: ").split()))
    matrix.append(row)
matrix = np.array(matrix)
print("Original Matrix:\n", matrix)
print("Transpose of the matrix:\n",matrix.T)


Enter 3 numbers for row 1: 1 3 7
Enter 3 numbers for row 2: 3 9 8
Enter 3 numbers for row 3: 2 7 8 
Original Matrix:
 [[1 3 7]
 [3 9 8]
 [2 7 8]]
Transpose of the matrix:
 [[1 3 2]
 [3 9 7]
 [7 8 8]]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])         #resized the matrix
new_matrix = np.resize(matrix, (3, 2))
print(new_matrix)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a=input("enter the 1st value of the sum:")           #sum with user input
b=input("enter the 2nd value of the sum:")
c=input("enter the third value of the sum:")

d=int(a)+int(b)+int(c)
print(d)

enter the 1st value of the sum:12
enter the 2nd value of the sum:23
enter the third value of the sum:12
47
